name = input('Введите ваши имя и фамилию')
age = input('Сколько вам лет?')
city = input('Где вы живёте?')
print(f'Ваши фамилия, имя {name}')
print(f'Ваш возраст {age}')
print(f'Вы живёте в {city}')